
# DataSource Config
spring:
  datasource:
    url: jdbc:p6spy:mysql://39.106.132.170:13016/zwkj_zhxt?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root


# Logger Config
logging:
  level:
    com.hki.mpdemo.sysuser.mapper: debug
# MyBatis-Plus 配置该演示无
server:
  port: 8088
